# Generated by Django 5.2.2 on 2026-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('board_or_university', models.CharField(max_length=200)),
                ('year_of_completion', models.IntegerField()),
                ('percentage_or_cgpa', models.CharField(max_length=20)),
            ],
        ),
    ]
